# Generated by Django 5.1.1 on 2024-12-05 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='discord_users',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('balance', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='jail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bust_time', models.DateTimeField()),
                ('fee', models.FloatField()),
                ('release_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='work',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('money', models.FloatField()),
            ],
        ),
    ]
