# Generated by Django 5.1.1 on 2024-12-05 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='discord_users',
            new_name='DiscordUsers',
        ),
        migrations.RenameField(
            model_name='work',
            old_name='text',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='work',
            old_name='id',
            new_name='work_id',
        ),
        migrations.RemoveField(
            model_name='work',
            name='money',
        ),
        migrations.AddField(
            model_name='work',
            name='description',
            field=models.TextField(default='Description'),
        ),
        migrations.AddField(
            model_name='work',
            name='tier',
            field=models.CharField(choices=[('I', 'First'), ('II', 'Second'), ('III', 'Third'), ('IV', 'Fourth')], default='I', max_length=3),
        ),
    ]
