# Generated by Django 5.1.1 on 2024-12-07 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_rename_discord_users_discordusers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(default='Description')),
                ('balance', models.FloatField(default=0.0)),
            ],
        ),
    ]
