# Generated by Django 5.1.1 on 2024-12-07 21:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='discordusers',
            name='work_cooldown',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 7, 22, 15, 41, 815448)),
        ),
    ]
