# Generated by Django 5.1.1 on 2024-12-07 21:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_discordusers_work_cooldown'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discordusers',
            name='work_cooldown',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 7, 21, 50, 12, 977815, tzinfo=datetime.timezone.utc)),
        ),
    ]
