# Generated by Django 5.1.1 on 2024-12-07 21:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_discordusers_work_cooldown'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discordusers',
            name='work_cooldown',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
