# Generated by Django 5.1.1 on 2024-12-19 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_remove_work_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.AddField(
            model_name='discordusers',
            name='tier',
            field=models.CharField(choices=[('I', 'First'), ('II', 'Second'), ('III', 'Third'), ('IV', 'Fourth')], default='I', max_length=3),
        ),
        migrations.AddField(
            model_name='work',
            name='balance',
            field=models.FloatField(default=0.0),
        ),
    ]
