# Generated by Django 5.1.1 on 2025-01-02 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_transaction_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payee_id',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='payer_id',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
