# Generated by Django 5.1.1 on 2025-01-05 18:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_transaction_payee_id_transaction_payer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='discordusers',
            name='crime_cooldown',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
