# Generated by Django 5.1.1 on 2025-01-11 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_bank_regularshopitem_tiershopitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='regularshopitem',
            name='cost',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='tiershopitem',
            name='cost',
            field=models.FloatField(default=0.0),
        ),
    ]
